// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Tag documents */
interface TagDocumentData {
    /**
     * name field in *Tag*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: tag.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * icon field in *Tag*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: tag.icon
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    icon: prismicT.ImageField<never>;
    /**
     * icon_url field in *Tag*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: tag.icon_url
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    icon_url: prismicT.KeyTextField;
    /**
     * is_skill field in *Tag*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: tag.is_skill
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    is_skill: prismicT.BooleanField;
}
/**
 * Tag document from Prismic
 *
 * - **API ID**: `tag`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TagDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<TagDocumentData>, "tag", Lang>;
/** Content for TopPage documents */
interface ToppageDocumentData {
    /**
     * description field in *TopPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: toppage.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * affiliation field in *TopPage*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: toppage.affiliation[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    affiliation: prismicT.GroupField<Simplify<ToppageDocumentDataAffiliationItem>>;
    /**
     * awards field in *TopPage*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: toppage.awards[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    awards: prismicT.GroupField<Simplify<ToppageDocumentDataAwardsItem>>;
    /**
     * contacts field in *TopPage*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: toppage.contacts[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    contacts: prismicT.GroupField<Simplify<ToppageDocumentDataContactsItem>>;
    /**
     * skills field in *TopPage*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: toppage.skills[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    skills: prismicT.GroupField<Simplify<ToppageDocumentDataSkillsItem>>;
}
/**
 * Item in TopPage → affiliation
 *
 */
export interface ToppageDocumentDataAffiliationItem {
    /**
     * viewId field in *TopPage → affiliation*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: toppage.affiliation[].viewid
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    viewid: prismicT.NumberField;
    /**
     * content field in *TopPage → affiliation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: toppage.affiliation[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    content: prismicT.KeyTextField;
}
/**
 * Item in TopPage → awards
 *
 */
export interface ToppageDocumentDataAwardsItem {
    /**
     * content field in *TopPage → awards*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: toppage.awards[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    content: prismicT.KeyTextField;
    /**
     * link field in *TopPage → awards*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: toppage.awards[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Item in TopPage → contacts
 *
 */
export interface ToppageDocumentDataContactsItem {
    /**
     * icon field in *TopPage → contacts*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: toppage.contacts[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    icon: prismicT.LinkToMediaField;
    /**
     * name field in *TopPage → contacts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: toppage.contacts[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * link field in *TopPage → contacts*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: toppage.contacts[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Item in TopPage → skills
 *
 */
export interface ToppageDocumentDataSkillsItem {
    /**
     * skill field in *TopPage → skills*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: toppage.skills[].skill
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    skill: prismicT.RelationField<"tag">;
}
/**
 * TopPage document from Prismic
 *
 * - **API ID**: `toppage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ToppageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ToppageDocumentData>, "toppage", Lang>;
/** Content for Work documents */
interface WorkDocumentData {
    /**
     * title field in *Work*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * cover image field in *Work*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: work.cover_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover_image: prismicT.ImageField<never>;
    /**
     * create at field in *Work*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: work.create_at
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    create_at: prismicT.TimestampField;
    /**
     * images field in *Work*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: work.images[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    images: prismicT.GroupField<Simplify<WorkDocumentDataImagesItem>>;
    /**
     * tags field in *Work*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: work.tags[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    tags: prismicT.GroupField<Simplify<WorkDocumentDataTagsItem>>;
    /**
     * short_description field in *Work*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work.short_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    short_description: prismicT.KeyTextField;
    /**
     * description field in *Work*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Work → images
 *
 */
export interface WorkDocumentDataImagesItem {
    /**
     * image field in *Work → images*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: work.images[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * description field in *Work → images*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: work.images[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Item in Work → tags
 *
 */
export interface WorkDocumentDataTagsItem {
    /**
     * tag field in *Work → tags*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: work.tags[].tag
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    tag: prismicT.RelationField<"tag">;
}
/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<WorkDocumentData>, "work", Lang>;
export type AllDocumentTypes = TagDocument | ToppageDocument | WorkDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { TagDocumentData, TagDocument, ToppageDocumentData, ToppageDocumentDataAffiliationItem, ToppageDocumentDataAwardsItem, ToppageDocumentDataContactsItem, ToppageDocumentDataSkillsItem, ToppageDocument, WorkDocumentData, WorkDocumentDataImagesItem, WorkDocumentDataTagsItem, WorkDocument, AllDocumentTypes };
    }
}
